name: CI/CD for FastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install fastapi uvicorn gunicorn

    - name: Test the application
      run: |
        python -m unittest discover tests

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_USER: ubuntu
        EC2_HOST: 13.61.104.249  
      run: |
        ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $EC2_USER@$EC2_HOST << EOF
          cd /var/www/html/Fastapi
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart nginx
        EOF
