name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run pipeline on pushes to the main branch
  pull_request:
    branches:
      - main  # Run pipeline on pull requests targeting main

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify Python version

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Tests
    - name: Run Tests
      run: pytest tests/  # Update path if your tests are in a different directory

    # Step 5: Deploy to Render
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
             -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
             -d ''

